### ISSUE TITLE
Happy Button Demo

### ISSUE THREAD

**Issue by thisseahorse** [thisseahorse/Happy-Button#1]
![happy button run once](https://user-images.githubusercontent.com/38790651/40490696-da57c6dc-5f31-11e8-9e21-191770f4b046.gif)

**Comment by operatesspaceships** [comment]
![happy button loop](https://user-images.githubusercontent.com/38790651/40491083-c4c0366e-5f32-11e8-9d8d-e95e5cb1cab5.gif)
